# Generated by Django 5.1.6 on 2025-02-24 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datalogger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "datalogger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="measurements.datalogger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("temp", "Temperature"),
                            ("rain", "Rainfall"),
                            ("hum", "Humidity"),
                        ],
                        max_length=4,
                    ),
                ),
                ("value", models.FloatField()),
                ("measured_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "datalogger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="measurements.datalogger",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="measurements.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datalogger", "measured_at"],
                        name="measurement_datalog_133f3f_idx",
                    ),
                    models.Index(
                        fields=["label", "measured_at"],
                        name="measurement_label_001853_idx",
                    ),
                    models.Index(
                        fields=["ingested_at"], name="measurement_ingeste_cafdf8_idx"
                    ),
                ],
            },
        ),
    ]
