# Generated by Django 5.1.6 on 2025-02-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("temp", "Temperature"),
                            ("rain", "Rainfall"),
                            ("hum", "Humidity"),
                        ],
                        max_length=4,
                    ),
                ),
                ("value", models.FloatField()),
                ("recorded_at", models.DateTimeField()),
                ("datalogger", models.UUIDField()),
                ("location", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datalogger", "recorded_at"],
                        name="measurement_datalog_457607_idx",
                    ),
                    models.Index(
                        fields=["label", "recorded_at"],
                        name="measurement_label_dbb17a_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="measurement_recorde_49a1df_idx"
                    ),
                ],
            },
        ),
    ]
